# Stage 1: Build the Angular application
FROM node:16-alpine AS build

WORKDIR /usr/local/app

COPY *.json ./

COPY ./ /usr/local/app

RUN npm install


RUN npm run build --aot=true --optimization=true



# Use a lightweight base image
FROM nginx:latest

# Copy the static website files to the Nginx document root
COPY --from=build /usr/local/app/dist/wd-fab /usr/share/nginx/html
COPY /nginx.conf  /etc/nginx/conf.d/default.conf
EXPOSE 80